### ISSUE TITLE
Going further than durability +dart craft grinding not working.

### ISSUE THREAD

**Issue by nalkrien** [portablejim/VeinMiner#1]
I am using the latest 0.8.2 and mod support 3.2 If I use a wood pickax and start veinmining and hold shift (my hotkey). It will keep going to the radius and not stop at the amount the pick can break. It will only give me the amount the pick can but destroy everything else. I have also did a grinding unbreakable pick in dartcraft and it does not do the grinding. All I had on the pick was the invulnerability core, a flint, and the rest speed.

**Comment by portablejim** [comment]
Is this with MInecraft 1.5 or 1.6?

**Comment by nalkrien** [comment]
1.6

**Comment by portablejim** [comment]
Should be fixed in 0.8.3
