### ISSUE TITLE
0.19.0.30

### ISSUE THREAD

**Issue by MindlessPuppetz** [portablejim/VeinMiner#10]
This version fixes the configuration files not saving, but in-game, VeinMiner does not seem to be working. Have tried several tools and blocks listed in files, with proper modes set in game, and seems to not want to work.

MC version: 1.7.10
Forge version: 1199
My general cfg: https://pastee.org/mgctp
My tools and blocks json: https://pastee.org/3dv6j

If you need any more information, let me know.

--edit--
ps: I do not see anything in my console regarding veinminer that hints at any issues.

**Comment by portablejim** [comment]
```
limit {
# Limit of blocks to be destroyed at once. Use -1 for infinite. [range: -1 to 2147483647, default: 800]
I:limit.blocks=0

# Maximum number of blocks to be removed per game tick (1/20 seconds). Using a low number will keep the game from getting huge performance drops but also decreases the speed at which blocks are destroyed. [range: 1 ~ 1000, default: 10]
I:limit.blocksPerTick=0

# Maximum distance from the first block to search for blocks to destroy. [range: -1 to 1000, default: 20]
I:limit.radius=0
```

They are all 0. This is probably left over from an old version you tried.

**Comment by MindlessPuppetz** [comment]
Ugh, will try again, I missed re-adding those values after the many config resets lol. Sorry to bother you.
