### ISSUE TITLE
Skyfactory 3

### ISSUE THREAD

**Issue by Emmil2** [portablejim/VeinMiner#104]
hello i am have downloaded the newest version of veinminer on this page and it keeps saying "you seem to have a veinminer on the client. please use /veinminerc instead"
but when i do that when i write /veinminerc sneak it will not work 
i don't know if it me who are stupid or but plz help me

**Comment by boudiccaeceni** [comment]
I'm getting the same error. It doesn't work when set to sneak or not sneak. Or when using the ~ key. I have no other mods, only one resource pack active. Playing v 1.11.2.
Any help appreciated.

**Comment by portablejim** [comment]
Sky factory 3 does not have Veinminer any more (so is now invalid).
