### ISSUE TITLE
Crash when using veinminer

### ISSUE THREAD

**Issue by schnotzler** [portablejim/VeinMiner#106]
In my newly created modpack my game crashes as soon as i use veinminer:

I use the activate on sneak option.

Crashlog: [Here](https://paste.ee/p/8OUKr)

ConsoleOutput: [GameOutput.txt](https://github.com/portablejim/VeinMiner/files/859108/GameOutput.txt)

I can try to give some more information of needed.

**Comment by portablejim** [comment]
Combining with #123
