### ISSUE TITLE
Startup message configuration

### ISSUE THREAD

**Issue by Senophoe** [portablejim/VeinMiner#108]
I currently work with modpacks, and one of the main problems we have is the huge ammount of messages that show on chat after login. Could you please add a config option to disable the VeinMiner's message? I couldn't find it on the configs...

The one that says _"Veinminer using client keybind. See mod config for details. Veinminer client keybind set to activate on pressing the key."_

Thank you,
Seno

**Comment by portablejim** [comment]
No

**Comment by jessiewestlake** [comment]
I have this same problem. We should be able to block this message on server or on client.

**Comment by Kizzycocoa** [comment]
I concur - this should be an option. With due respect, tons of mods have startup text/new-game manuals, almost all of them have ways to stop it. I feel it's rather arrogant to simply shoot this down with a no. If all the other modders had the same attitude, the problem would be far worse, and no-one's messages would be seen. Especially when, with all due respect, the message is a verbose way of saying "mod loaded".

The message is absolutely superfluous, it says a keybind the mod programmed into the game, is in the game. It is no better than a "this mod is installed" announcement. It should be disabled by default, frankly.
