### ISSUE TITLE
VeinMiner-1.7.10_0.20.0 - Wont Save Config Changes

### ISSUE THREAD

**Issue by Lanse505** [portablejim/VeinMiner#11]
Hello! 

I'm currently testing VeinMiner-1.7.10_0.20.0 and I've finally finished my configs (after several hours of tedious work), however every single time I boot up Minecraft it keeps clearing the configs I've made and replaces them with Default Veinminer Configs. This is quiet annoying cause i added alot of blocks and tools that I have in my current testing pack. I've disabled it auto-detecting tools incase that was overriding it and it still doesn't work :/.

My Configs:
General: http://pastebin.com/pfLtQzC2
Tool-JSON: http://pastebin.com/4r2fpFCk

Anyway thx ahead of time 
// Lanse505

**Comment by portablejim** [comment]
Your tool JSON file is incorrect.

Line 96: Extra comma
Line 329: Missing comma
Line 343: Extra comma

You can parse json online at sites like http://jsonformatter.curiousconcept.com/

**Comment by Lanse505** [comment]
After alittle tinkering and alot of help from you, i'm pleased to say the Veinminer Configs are working smoothly now <3
