### ISSUE TITLE
Can This Mod Use For Clients Only / Non-Forge Way?

### ISSUE THREAD

**Issue by RedPhoenix135** [portablejim/VeinMiner#110]
Can I Use This Mod Without Forge?
I Hope I Can Use This Without Forge :)

Thanks!

-BluePhoenix135
Date Issue: May 22, 2017 (5/22/17)

**Comment by portablejim** [comment]
This is mainly a server sided mod. You can use it without the mod on the client side, but not if it is not on the server side. It also requires forge.
