### ISSUE TITLE
Tools and blocks reapper in the config after deletion

### ISSUE THREAD

**Issue by Irdes** [portablejim/VeinMiner#113]
Steps to reproduce:
1) Go to pickaxes list, delete all entries
2) Restart minecraft
3) Go to the same menu
4) tconstruct:pickaxe is there even though it shouldn't

Also:
1) Go to pickaxe blocks list, delete all entries
2) Restart minecraft
3) Go to the same menu
4) Vanilla ores that don't drop blocks (non-metal ores) are back. That includes coal, redstone, diamond, emerald, lapis and quartz.

**Comment by portablejim** [comment]
Try disabling autodetect in the modsupport.cfg file.
