### ISSUE TITLE
Forge Config Bug

### ISSUE THREAD

**Issue by Surawsome** [portablejim/VeinMiner#116]
I have the latest version of forge. I went to the mods section in the main menu and went to the config option for Vein Miner and my minecraft started freaking out. I'm not sure if this is a bug with the mod or forge.

**Comment by Surawsome** [comment]
Here is a video of the problem https://youtu.be/V0KxjIRizDA

**Comment by Miki387** [comment]
I translate English by automatic translation.
I also get the same error.
After that, this sentence is displayed.
```
The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: net.minecraft.client.renderer.Tessellator.func_178180_c()Lnet/minecraft/client/renderer/VertexBuffer;
```
The version forge is 1.12-14.21.0.2330.
