### ISSUE TITLE
Is it possible to use swapping wand with veinminer?

### ISSUE THREAD

**Issue by donqixot** [portablejim/VeinMiner#128]
In the mod called "Not Enough Wands" (https://minecraft.curseforge.com/projects/not-enough-wands) there is swapping wand, which allows you to swap world's blocks with the block in your inventory. For instance you can swap diamond_ore you found with cobblestone in your inventory. I tried to put that tool (notenoughwands:swapping_wand) in the pickaxe section of veinminer config, but that does not help. Is this because how the tool handles breaking blocks or because some interaction between that mod and veinminer? I am using 1.12.2, veinminer version 1.12-0.38.1.639+134fb1e.jar, forge version 14.23.0.2486, not_enough_wands version 1.12-1.5.9.

**Comment by portablejim** [comment]
No, you cannot.
