### ISSUE TITLE
Init-Crash :P

### ISSUE THREAD

**Issue by Lanse505** [portablejim/VeinMiner#15]
Hello I've been haveing this random crash after adding some things to my veinminer configs. My Veinminer Configs should be properly set-up and i've checked it twice. Could I maybe get some help ^^' so i know i'm not going crazy.

Crash: http://pastebin.com/E58pEtCh

Veinminer Configs: http://pastebin.com/zLEnBFHJ

**Comment by portablejim** [comment]
You have a null in there. Line 286.

**Comment by Lanse505** [comment]
wonder how that got there o.o

**Comment by Lanse505** [comment]
So Jim i might have a problem, I remove the Null from the configs, save them and then proceed to launch my game, where on the game crashes with that same crashlog and proceeds yet again to generate that Null line in my Hoe configs o.o

**Comment by portablejim** [comment]
Did you remove the comma from the last value before the null?

**Comment by Lanse505** [comment]
... Excuse me while i facepalm myself into oblivion XD, totally missed the comma x.x

**Comment by Lanse505** [comment]
Thank you Jim i've fixed it now ^^
