### ISSUE TITLE
[1.12.2] Can't veinmine anything with shears (and possible issue with TC leaves)

### ISSUE THREAD

**Issue by DarkenedSpirit** [portablejim/VeinMiner#158]
I'm using Forge 1.12.2-14.23.5.2847 and VeinMiner-1.12-0.38.2.647+b31535a.

I was trying to veinmine some Purple Slimy Leaves fron Tinkers' Construct, and I could not.
Tried to add all three variants to VeinMiner's blocklist, resulting in continuos crashes on game start during mod loading, without crash report.
Deleted VeinMiner's config to get rid of the problem and turned back to square one; after this, I made some tests only to realise the problem is bigger than I thought: the vanilla shears can't veinmine ANY type of leaves, vanilla or modded, in survival mode, but for some reason they can be used to veinmine everything else

**Comment by DarkenedSpirit** [comment]
Other possibly useful informations:

Using Mantle 1.12-1.3.3.49 and TConstruct-1.12.2-2.12.0.135

Edited VeinMiner's general config: override.allBlocks and override.allTools are both true

Created a specific installation with only VeinMiner, Mantle and TC to double-check, both with default and edited configs. Nothing changed

**Comment by niubiclas** [comment]
hello，how can i download it
