### ISSUE TITLE
[Crash] ConcurrentModificationException

### ISSUE THREAD

**Issue by shadowfacts** [portablejim/VeinMiner#17]
http://pastebin.ubuntu.com/9556571/

I was just VeinMining some stone like normal, when I crash because of a `java.util.ConcurrentModificationException`. No idea what caused this, this has never happened to me before.

**Comment by Yorkforce** [comment]
Running Java 8?

Try Java 7 if so.

**Comment by shadowfacts** [comment]
Nope, just using normal Java 7 JRE.

**Comment by portablejim** [comment]
Doesn't seem to be a problem with VeinMiner.
