### ISSUE TITLE
update to 1.8

### ISSUE THREAD

**Issue by loordgek** [portablejim/VeinMiner#18]
hi when are you going th update to 1.8?

**Comment by portablejim** [comment]
When I get around to it.

**Comment by portablejim** [comment]
I have started. https://github.com/portablejim/VeinMiner/tree/1.8

**Comment by loordgek** [comment]
:+1:

**Comment by RebaLynn1960** [comment]
I am glad you are working on it. I am slowly building a mod pack for 1.8 :)

**Comment by portablejim** [comment]
I think this is enough to close: http://minecraft.curseforge.com/mc-mods/67133-veinminer/files/2228404
