### ISSUE TITLE
Veinminer 0.25.0.1 (MC 1.8) 

### ISSUE THREAD

**Issue by kreezxil** [portablejim/VeinMiner#21]
Veinminer 0.25.0.1 (MC 1.8) won't allow the client to connect to the server, the same version is on both the client and server. The server refuses the client saying that veinminer 0.25.0 is not installed.

fml-client-latest: http://paste.ee/p/Y5G2H

**Comment by portablejim** [comment]
This is fixed in bbd4d1ba65fe9d49c521bc0da6ef233411e72f04

**Comment by kreezxil** [comment]
cool thanks.
