### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by blockbreaker1361** [portablejim/VeinMiner#24]
I get a crash in the latest 0.27.0 version. I also posted this on the Draconic Evolution site.

http://pastebin.com/efFKQ6fx

**Comment by portablejim** [comment]
Not VeinMiner's problem.

However, you could write a better bug report:
1) Include what you were doing when it crashed.
2) Include the whole of the crash log (i.e. the stuff at the end telling me stuff like what version of minecraft and what version of the other mods you are playing with).
