### ISSUE TITLE
Not working with mod "ex-astris"

### ISSUE THREAD

**Issue by wooby6** [portablejim/VeinMiner#26]
in particular the "exastris:hammer_rf"
funny enough the crook "exastris:Crook_Rf" works fine

Config listed is below,

note that id 4852 is the same as "exastris:hammer_rf", I attempted to add it twice in a attempt to resolve the issues, I got the item names from MineTweaker 3 just removed the "<>"

{
  "tools": {
    "axe": {
      "name": "Axe",
      "icon": "minecraft:diamond_axe",
      "toollist": [
        "TConstruct:hatchet",
        "ThermalFoundation:tool.axeBronze",
        "ThermalFoundation:tool.axeCopper",
        "ThermalFoundation:tool.axeElectrum",
        "ThermalFoundation:tool.axeInvar",
        "ThermalFoundation:tool.axeLead",
        "ThermalFoundation:tool.axeNickel",
        "ThermalFoundation:tool.axePlatinum",
        "ThermalFoundation:tool.axeSilver",
        "ThermalFoundation:tool.axeTin",
        "appliedenergistics2:item.ToolCertusQuartzAxe",
        "appliedenergistics2:item.ToolNetherQuartzAxe",
        "minecraft:diamond_axe",
        "minecraft:golden_axe",
        "minecraft:iron_axe",
        "minecraft:stone_axe",
        "minecraft:wooden_axe"
      ],
      "blocklist": [
        "5",
        "BiomesOPlenty:appleLeaves",
        "BiomesOPlenty:colorizedLeaves1",
        "BiomesOPlenty:colorizedLeaves2",
        "BiomesOPlenty:leaves1",
        "BiomesOPlenty:leaves2",
        "BiomesOPlenty:leaves3",
        "BiomesOPlenty:leaves4",
        "BiomesOPlenty:logs1/0",
        "BiomesOPlenty:logs1/1",
        "BiomesOPlenty:logs1/2",
        "BiomesOPlenty:logs1/3",
        "BiomesOPlenty:logs2/0",
        "BiomesOPlenty:logs2/1",
        "BiomesOPlenty:logs2/2",
        "BiomesOPlenty:logs2/3",
        "BiomesOPlenty:logs3/0",
        "BiomesOPlenty:logs3/1",
        "BiomesOPlenty:logs3/2",
        "BiomesOPlenty:logs3/3",
        "BiomesOPlenty:logs4/0",
        "BiomesOPlenty:logs4/1",
        "BiomesOPlenty:logs4/2",
        "BiomesOPlenty:persimmonLeaves",
        "Forestry:fireproofLog1",
        "Forestry:fireproofLog2",
        "Forestry:fireproofLog3",
        "Forestry:fireproofLog4",
        "Forestry:fireproofLog5",
        "Forestry:fireproofLog6",
        "Forestry:fireproofLog7",
        "Forestry:fireproofLog8",
        "Forestry:leaves",
        "Forestry:log1",
        "Forestry:log2",
        "Forestry:log3",
        "Forestry:log4",
        "Forestry:log5",
        "Forestry:log6",
        "Forestry:log7",
        "Forestry:log8",
        "MineFactoryReloaded:",
        "MineFactoryReloaded:rubberwood.log",
        "Natura:Dark Leaves",
        "Natura:Dark Tree/0",
        "Natura:Dark Tree/1",
        "Natura:Rare Leaves",
        "Natura:Rare Tree/0",
        "Natura:Rare Tree/1",
        "Natura:Rare Tree/2",
        "Natura:Rare Tree/3",
        "Natura:floraleaves",
        "Natura:floraleavesnocolor",
        "Natura:redwood/1",
        "Natura:tree/0",
        "Natura:tree/1",
        "Natura:tree/2",
        "Natura:tree/3",
        "Natura:willow/0",
        "Oak_Wood_Planks",
        "Thaumcraft:blockMagicalLog/0",
        "Thaumcraft:blockMagicalLog/1",
        "minecraft:fence",
        "minecraft:leaves",
        "minecraft:leaves2",
        "minecraft:log",
        "minecraft:log2",
        "minecraft:planks"
      ]
    },
    "crook": {
      "name": "Crook",
      "icon": "exnihilo:crook",
      "toollist": [
        "exastris:crook_rf",
        "exnihilo:crook",
        "exnihilo:crook_bone"
      ],
      "blocklist": [
        "Ex",
        "exnihilo:infested_leaves",
        "minecraft:leaves",
        "minecraft:leaves2",
        "minecraft:tallgrass",
        "minecraft:vine",
        "minecraft:web",
        "minecraft:wool"
      ]
    },
    "hammer": {
      "name": "Hammer",
      "icon": "exnihilo:hammer_stone",
      "toollist": [
        "4852",
        "exastris:hammer_rf",
        "exnihilo:hammer_diamond",
        "exnihilo:hammer_gold",
        "exnihilo:hammer_iron",
        "exnihilo:hammer_stone",
        "exnihilo:hammer_wood"
      ],
      "blocklist": [
        "exnihilo:aluminum_dust",
        "exnihilo:aluminum_gravel",
        "exnihilo:aluminum_sand",
        "exnihilo:copper_dust",
        "exnihilo:copper_gravel",
        "exnihilo:copper_sand",
        "exnihilo:dust",
        "exnihilo:ender_lead_gravel",
        "exnihilo:ender_platinum_gravel",
        "exnihilo:ender_silver_gravel",
        "exnihilo:ender_tin_gravel",
        "exnihilo:exnihilo.gravel_ender",
        "exnihilo:exnihilo.gravel_nether",
        "exnihilo:gold_dust",
        "exnihilo:gold_gravel",
        "exnihilo:gold_sand",
        "exnihilo:iron_dust",
        "exnihilo:iron_gravel",
        "exnihilo:iron_sand",
        "exnihilo:lead_dust",
        "exnihilo:lead_gravel",
        "exnihilo:lead_sand",
        "exnihilo:nether_copper_gravel",
        "exnihilo:nether_gold_gravel",
        "exnihilo:nether_iron_gravel",
        "exnihilo:nether_nickel_gravel",
        "exnihilo:nickel_dust",
        "exnihilo:nickel_gravel",
        "exnihilo:nickel_sand",
        "exnihilo:platinum_dust",
        "exnihilo:platinum_gravel",
        "exnihilo:platinum_sand",
        "exnihilo:silver_dust",
        "exnihilo:silver_gravel",
        "exnihilo:silver_sand",
        "exnihilo:tin_dust",
        "exnihilo:tin_gravel",
        "exnihilo:tin_sand",
        "minecraft:cobblestone",
        "minecraft:gravel",
        "minecraft:sand"
      ]
    },
    "hoe": {
      "name": "Hoe",
      "icon": "minecraft:diamond_hoe",
      "toollist": [
        "TConstruct:mattock",
        "ThermalFoundation:tool.hoeBronze",
        "ThermalFoundation:tool.hoeCopper",
        "ThermalFoundation:tool.hoeElectrum",
        "ThermalFoundation:tool.hoeInvar",
        "ThermalFoundation:tool.hoeLead",
        "ThermalFoundation:tool.hoeNickel",
        "ThermalFoundation:tool.hoePlatinum",
        "ThermalFoundation:tool.hoeSilver",
        "ThermalFoundation:tool.hoeTin",
        "appliedenergistics2:item.ToolCertusQuartzHoe",
        "appliedenergistics2:item.ToolNetherQuartzHoe",
        "minecraft:diamond_hoe",
        "minecraft:golden_hoe",
        "minecraft:iron_hoe",
        "minecraft:stone_hoe",
        "minecraft:wooden_hoe"
      ],
      "blocklist": [
        "minecraft:carrots",
        "minecraft:melon_block",
        "minecraft:potatoes",
        "minecraft:pumpkin",
        "minecraft:wheat"
      ]
    },
    "pickaxe": {
      "name": "Pickaxe",
      "icon": "minecraft:diamond_pickaxe",
      "toollist": [
        "RedstoneArsenal:tool.pickaxeFlux",
        "TConstruct:pickaxe",
        "ThermalFoundation:tool.pickaxeBronze",
        "ThermalFoundation:tool.pickaxeCopper",
        "ThermalFoundation:tool.pickaxeElectrum",
        "ThermalFoundation:tool.pickaxeInvar",
        "ThermalFoundation:tool.pickaxeLead",
        "ThermalFoundation:tool.pickaxeNickel",
        "ThermalFoundation:tool.pickaxePlatinum",
        "ThermalFoundation:tool.pickaxeSilver",
        "ThermalFoundation:tool.pickaxeTin",
        "appliedenergistics2:item.ToolCertusQuartzPickaxe",
        "appliedenergistics2:item.ToolNetherQuartzPickaxe",
        "minecraft:diamond_pickaxe",
        "minecraft:golden_pickaxe",
        "minecraft:iron_pickaxe",
        "minecraft:stone_pickaxe",
        "minecraft:wooden_pickaxe"
      ],
      "blocklist": [
        "BigReactors:YelloriteOre/0",
        "BiomesOPlenty:gemOre/2",
        "BiomesOPlenty:gemOre/4",
        "BiomesOPlenty:gemOre/6",
        "BiomesOPlenty:gemOre/8",
        "BiomesOPlenty:gemOre/10",
        "BiomesOPlenty:gemOre/12",
        "BiomesOPlenty:gemOre/14",
        "Forestry:resources/0",
        "Forestry:resources/1",
        "Forestry:resources/2",
        "NetherOres:tile.netherores.ore.0/0",
        "NetherOres:tile.netherores.ore.0/1",
        "NetherOres:tile.netherores.ore.0/2",
        "NetherOres:tile.netherores.ore.0/3",
        "NetherOres:tile.netherores.ore.0/4",
        "NetherOres:tile.netherores.ore.0/5",
        "NetherOres:tile.netherores.ore.0/6",
        "NetherOres:tile.netherores.ore.0/7",
        "NetherOres:tile.netherores.ore.0/8",
        "NetherOres:tile.netherores.ore.0/9",
        "NetherOres:tile.netherores.ore.0/10",
        "NetherOres:tile.netherores.ore.1/0",
        "NetherOres:tile.netherores.ore.1/1",
        "NetherOres:tile.netherores.ore.1/14",
        "TConstruct:GravelOre/0",
        "TConstruct:GravelOre/1",
        "TConstruct:GravelOre/2",
        "TConstruct:GravelOre/3",
        "TConstruct:GravelOre/4",
        "TConstruct:GravelOre/5",
        "TConstruct:SearedBrick/1",
        "TConstruct:SearedBrick/2",
        "TConstruct:SearedBrick/3",
        "TConstruct:SearedBrick/4",
        "TConstruct:SearedBrick/5",
        "Thaumcraft:blockCustomOre/0",
        "Thaumcraft:blockCustomOre/1",
        "Thaumcraft:blockCustomOre/2",
        "Thaumcraft:blockCustomOre/3",
        "Thaumcraft:blockCustomOre/4",
        "Thaumcraft:blockCustomOre/5",
        "Thaumcraft:blockCustomOre/6",
        "Thaumcraft:blockCustomOre/7",
        "ThermalFoundation:Ore/0",
        "ThermalFoundation:Ore/1",
        "ThermalFoundation:Ore/2",
        "ThermalFoundation:Ore/3",
        "ThermalFoundation:Ore/4",
        "ThermalFoundation:Ore/5",
        "ThermalFoundation:Ore/6",
        "appliedenergistics2:tile.OreQuartz/0",
        "appliedenergistics2:tile.OreQuartzCharged/0",
        "minecraft:coal_ore",
        "minecraft:cobblestone_wall",
        "minecraft:diamond_ore",
        "minecraft:emerald_ore",
        "minecraft:glowstone",
        "minecraft:gold_ore",
        "minecraft:iron_ore",
        "minecraft:lapis_ore",
        "minecraft:lit_redstone_ore",
        "minecraft:mossy_cobblestone",
        "minecraft:nether_brick_fence",
        "minecraft:obsidian",
        "minecraft:quartz_ore",
        "minecraft:redstone_ore"
      ]
    },
    "shears": {
      "name": "Shears",
      "icon": "minecraft:shears",
      "toollist": [
        "RedstoneArsenal:tool.wrenchFlux",
        "ThermalFoundation:tool.shearsBronze",
        "ThermalFoundation:tool.shearsCopper",
        "ThermalFoundation:tool.shearsElectrum",
        "ThermalFoundation:tool.shearsInvar",
        "ThermalFoundation:tool.shearsLead",
        "ThermalFoundation:tool.shearsNickel",
        "ThermalFoundation:tool.shearsPlatinum",
        "ThermalFoundation:tool.shearsSilver",
        "minecraft:shears"
      ],
      "blocklist": [
        "BiomesOPlenty:appleLeaves",
        "BiomesOPlenty:colorizedLeaves1",
        "BiomesOPlenty:colorizedLeaves2",
        "BiomesOPlenty:leaves1",
        "BiomesOPlenty:leaves2",
        "BiomesOPlenty:leaves3",
        "BiomesOPlenty:leaves4",
        "BiomesOPlenty:persimmonLeaves",
        "Forestry:leaves",
        "Natura:Dark Leaves",
        "Natura:Rare Leaves",
        "Natura:floraleaves",
        "Natura:floraleavesnocolor",
        "minecraft:deadbush",
        "minecraft:leaves",
        "minecraft:leaves2",
        "minecraft:tallgrass",
        "minecraft:vine",
        "minecraft:web",
        "minecraft:wool"
      ]
    },
    "shovel": {
      "name": "Shovel",
      "icon": "minecraft:diamond_shovel",
      "toollist": [
        "RedstoneArsenal:tool.shovelFlux",
        "TConstruct:mattock",
        "TConstruct:shovel",
        "ThermalFoundation:tool.shovelBronze",
        "ThermalFoundation:tool.shovelCopper",
        "ThermalFoundation:tool.shovelElectrum",
        "ThermalFoundation:tool.shovelInvar",
        "ThermalFoundation:tool.shovelLead",
        "ThermalFoundation:tool.shovelNickel",
        "ThermalFoundation:tool.shovelPlatinum",
        "ThermalFoundation:tool.shovelSilver",
        "ThermalFoundation:tool.shovelTin",
        "appliedenergistics2:item.ToolCertusQuartzSpade",
        "appliedenergistics2:item.ToolNetherQuartzSpade",
        "minecraft:diamond_shovel",
        "minecraft:golden_shovel",
        "minecraft:iron_shovel",
        "minecraft:stone_shovel",
        "minecraft:wooden_shovel"
      ],
      "blocklist": [
        "minecraft:clay",
        "minecraft:gravel"
      ]
    }
  }
}

**Comment by portablejim** [comment]
How are the crook and hammer different?
If they have the same ID, then they probably have different meta. Use the slash to add the metadata of the hammer.

**Comment by wooby6** [comment]
no the crook_rf has a different ID its "4853" in my game, the main difference between ex-nihilo tools and the ex-astris tools is that the ex-astris ones are RF powered, but I doubt  that would break anything

**Comment by wooby6** [comment]
OK update time. 
Iv'e just discovered that the "hammer_rf" does indeed work with VeinMiner.
Just not with cobblestone

**Comment by Blue64** [comment]
On a side note:

```
Outside of [ code ] tag.
` ` `
Inside of [ code ] tag.
` ` `
Outside of [ code ] tag.
[ code ]
Inside of [ code ] tag.
[ / code ]
Outside of [ code ] tag. It even adds a scroll bar if the line gets really super long, which I'm demonstrating on this line here.
Useful for using <these>
Note: remove the spaces between the [ & ] & ` as they are only there to avoid breaking this code tag. Also # will quick reference any issues in this repository (eg. This is issue #26)
Also, (Words)[http://www.tinyurl.com)
Would read "Words" but be a link to that link.
* Bullet 1
  * Bullet 2
    * Bullet 3
* Bullet 1
Added to the previous Bullet
Added to the previous Bullet

Not added to the previous Bullet
```

That's pretty much 90% of any GitHub formatting you'll need lol
