### ISSUE TITLE
Interesting issue between Ex Nihilo 2 and Veinminer

### ISSUE THREAD

**Issue by kreezxil** [portablejim/VeinMiner#28]
one or both is spamming the server console, but there is no associated crash.

also reported to veinminer

http://pastebin.com/jhJr1uT1

http://pastebin.com/4KyR6Sjm

**Comment by huntdogy** [comment]
veinminer you cannot use with ex Nihilo do to sertain things your better off takeing off veinminer

**Comment by kreezxil** [comment]
It's not crashing the game either, I was just reporting the spam error. It works fine with Ex Nihilo 2 and the old version worked fine with Ex Nihilo Original Flavor.
