### ISSUE TITLE
Blocks deleted by Veinminer

### ISSUE THREAD

**Issue by donqixot** [portablejim/VeinMiner#37]
If I place torches on every iron ore block and then mine iron with Veinminer, then only one torch attached to the very first block will be dropped, all other torches disapper. Same with cocoa beans on jungle trees, also flowers, grass and all vegetation on grass block (when grass blocks are whitelisted). Is this a feature? Can this be disabled in config?

**Comment by Blue64** [comment]
It's definitely **_NOT**_ a config option. I was curious why my seed drops were lower using VeinMiner on Grass, this would explain it. Have you tested it by breaking a ore that doesn't have a torch attached to start it? I could have sworn I was getting my dropped torches on the Stone. Also make sure you're not simply picking up a single stack, as they may simply all be dropping from the same spot, just like the blocks do, and stacking as a result, thus appearing as a single torch.

**Comment by portablejim** [comment]
Should be fixed now (0.31.0)
