### ISSUE TITLE
Blocklist ids in config shuffle around

### ISSUE THREAD

**Issue by uberfuzzy** [portablejim/VeinMiner#4]
VM 0.12.2
MC 1.6.4
Pack: FTB Monster 1.1.1
MCP 8.11
FML 6.4.49.965
Forge 9.11.1.965

I started keeping my config folder in a git repo, so that I could watch changes as mods update, and rollback as needed. (also so I could slowly build a personal ultimate VM config)
I noticed something that happened to the VM configs each time I load up minecraft (not even enter a world, just start it to logo screen)

![veinminer_config_shuffle](https://cloud.githubusercontent.com/assets/1438723/2782021/ce3cba6a-cb1a-11e3-943d-20bd0b179922.png)

Some chunks of IDs in the block lists would just shuffle around at will, but not the whole line. 
The line shown was for shovel, but also seen often on pickaxe. Not sure if it happens to others, dont need to add many blocks to other tools.

In case the image above is missing, what I'm explaining is a random chunk of IDs, lets say "A,B,C,D,E" would suddenly become "A,C,D,B,E"

**Comment by portablejim** [comment]
Fixed in 1.7.10 version.
