### ISSUE TITLE
[1.8.9] Mod Compatibility: Tinker's Construct (Minor)

### ISSUE THREAD

**Issue by claws61821** [portablejim/VeinMiner#43]
Minecraft 1.8.9
Forge 1.8.9-11.15.0.1695
Mantle 1.8.8-0.6
Tinker's Construct 1.8.8-2.0.1
Vein Miner 1.8.9-0.31.2

I'm running the above mods (and others) in default configuration, except for having added several TCon tools to Vein Miner using the "TConstruct:[tool]" ID format.

My testing has not been extensive, but I can confirm that Vein Miner works with Vanilla tools.

Preliminary testing concludes that Vein Miner currently does not work with the following Tinker's Construct tools:
Shovel
Pickaxe
Hatchet
Excavator
Hammer

I recognize that this is a minor issue, and that it might be sourced in the other relevant mod (which is currently undergoing a complete overhaul), but I thought that I should see whether you have any recommended action for me to attempt in case this is a simple case of ID10T or PEBKAC.

Thank you for your time.

**Comment by portablejim** [comment]
Try with lower case, as it is case sensitive.

**Comment by claws61821** [comment]
I've just tried again with the hatchet using all lowercase in both modname and toolname. Holding the activation key, the hatchet still breaks only the single log block at which I'm aiming. I'm using the Mod Options menu to add the tools, if that makes any difference.

**Comment by portablejim** [comment]
Try in-game, using the command. For the tool name, use F3+H to show the tool id/name and add it that way.

**Comment by claws61821** [comment]
It's working now, thank you. Forgot to check before making the latest change, so I'm not sure whether I simply had to reload the world (or relaunch the pack) after changing the config in Mod Options, or if inputting one of the tools via the command console kickstarted the others that had been added the new way.

Confirmed PEBKAC, Status Resolved, Closing Thread

**Comment by GazbonicAcid** [comment]
[That was how I added them.
Still doesn't work.](https://github.com/portablejim/VeinMiner/issues/51)

I have the following mods and version at their default configs.
BaseMetals 1.7.4
ElectricAdvantage 1.1.2
Enchiridion 1.8.9=3.0.1
Just Enough Items 1.8.9-2.28.9.176
MalisisCore 1.8.9-2.1.2
MalisisDoors 1.8.9-3.1.1
MalisisSwitches 1.8.9-1.0.1
Mantle 1.8.9-0.9.2
MCMultiPart 1.0.8
PowerAdvantag 1.5.4
Psi beta-23
SteamAdvantage 1.5.3
Tinkers Construct 1.8.9 2.2.0b
VeinMiner 1.8.9 0.31.4.unknown
