### ISSUE TITLE
ease configuration

### ISSUE THREAD

**Issue by MaPePeR** [portablejim/VeinMiner#5]
I think the ToolTypes should not be fixed in code, but read entirely from the configuration file. The simplest thing would be to add a 

```
validtools=pickaxe,axe,hoe,...
```

to the configuration file.

This would also increase compatibility with mods that add new types of toolsets (i look at you, ex nihilo)

Also it would be GREAT, if one could use blocknames instead of ids, in the configuration, which would allow to move one configuration to different modpacks more easily.

What do you think about it and if i would start working on something like this would you add it?

**Comment by portablejim** [comment]
The problem I have with dynamic tools is that, as far as I see it the help text / auto-completion not working properly. I am also trying not to have too many changes to the 1.5/1.6 version (master branch), instead wanting to develop the 1.7 version (1.7 branch). So if you can get it working in a nice way I'll add it to 1.7 and maybe even 1.5/1.6.

Block & Tool names are in 1.7. The problem with names in 1.5 & 1.6 is that names are not required and can actually cause crashes (yes, some mods _cough_BOP_cough_ crash when you ask for the name in 1.6)

**Comment by MaPePeR** [comment]
Yea, i just noticed the blocknames in the 1.7 branch. 

So i should base my changes on the 1.7 branch?

Edit: is the 1.7 branch functional at the moment, or not yet ready?

**Comment by portablejim** [comment]
It's functional, but I am still doing some fixing up.

**Comment by MaPePeR** [comment]
Hmm... i could not really make that version work/mine stuff :/ Any tips on what i'm doing wrong?

**Comment by portablejim** [comment]
You were probably holding shift instead of grave/tilda (configurable in controls). I have also pushed to the repo with the main changes I wanted to make. Also to consider is the configuration screen (Main menu => Mods => Vein Miner => Config) that is fairly fixed to the specified tools.

**Comment by MaPePeR** [comment]
I tried both - Grave and Shift - and used `/veinminer mode` to set it to sneak and try sneak again - could not veinmine anything. Using Forge `1.7.2-Recommended 10.12.1.1060` src-version. :/
