### ISSUE TITLE
[1.8.9] Mod Compatibility: Tinker's Construct (medium)

### ISSUE THREAD

**Issue by GazbonicAcid** [portablejim/VeinMiner#51]
[1.8.9] Mod Compatibility: Tinker's Construct (medium)
What [claws61821](https://github.com/portablejim/VeinMiner/issues/43) did to fix it doesn't work for me.
I put "(medium)" because the issue is back.
For me at least.

I have the following mods and version at their default configs.
BaseMetals 1.7.4
ElectricAdvantage 1.1.2
Enchiridion 1.8.9=3.0.1
Just Enough Items 1.8.9-2.28.9.176
MalisisCore 1.8.9-2.1.2
MalisisDoors 1.8.9-3.1.1
MalisisSwitches 1.8.9-1.0.1
Mantle 1.8.9-0.9.2
MCMultiPart 1.0.8
PowerAdvantag 1.5.4
Psi beta-23
SteamAdvantage 1.5.3
Tinkers Construct 1.8.9 2.2.0b
VeinMiner 1.8.9 0.31.4.unknown

**Comment by claws61821** [comment]
If you're using Veinminer on a multiplayer server, make sure that you have added the tools to the server-side Veinminer configuration as well. This can be done either through Veinminer's configuration files directly or using the old configuration commands via the server launch command shell interface.

**Comment by JCMais** [comment]
@claws61821 what were the ids you added to VeinMiner configuration for TInker's btw?

**Comment by claws61821** [comment]
@JCMais 
`tconstruct:battleaxe`
`tconstruct:hatchet`
`tconstruct:lumberaxe`
`tconstruct:mattock`
`tconstruct:hammer`
`tconstruct:pickaxe`
`tconstruct:shovel`
`tconstruct:excavator`
All of these work exactly as typed. Do not capitalize them.
`/veinminer axe toollist add tconstruct:hatchet`
`/veinminer saveconfig`
On your server box, type that into the console. The client-side console will not work for setting the server-side configuration. If you do not have access to the physical box or to a shell terminal, the configuration webpage that your hosting company provides probably holds a console entry dialogue box you can use for this.

You will still have to add the entries to your client-side configuration, but they will not work until you add them server-side.
