### ISSUE TITLE
Veinminer and Actually Additions

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [portablejim/VeinMiner#59]
I can't seem to get the Actually Additions drill to work with veinminer. I type in actuallyadditions:itemDrill in the config and it finds it, but when I attempt to use it, it continues to just mine one block. Maybe something with NBT or meta data?

**Comment by ghost** [comment]
Also add it to modSupport.cfg special_snowflake_tools section.

**Comment by xenoflot** [comment]
Confirmed just now. 

It needs to be both in the **tools-and-blocks.json** as a valid tool for Shovel and Pick, plus listed in **modsupport.cfg** as a special snowflake.

actuallyadditions:itemDrill   is the correct entry to use in both. Don't forget the commas and brackets in the JSON.

@portablejim Can close this one now, Jim. I think OP forgot about it.

**Comment by awkwaRdcaRRot** [comment]
Oops, I thought I had closed this already. Thanks for the follow up!
