### ISSUE TITLE
Crash while trying to use TiC Lumber Axe

### ISSUE THREAD

**Issue by steelshot** [portablejim/VeinMiner#60]
Whenever i try to break a tree with any Lumber Axe from TiC i crash, only the client, i removed all items and blocks from the configs as i have TreeCapitator, i only need veinminer for ores.

But it still keeps crashing
http://pastebin.com/CFWD2udJ

Also It would be nice to have global config options to enable/disable functions completely, so it would just not look for items but be completely disabled. Something like this.

B:Axe_Integration=true/false
B:Pickaxe_Integration=true/false
B:Shovel_Integration=true/false
B:Hoe_Integration=true/false
and so on..

**Comment by portablejim** [comment]
Your analysis of the problem is wrong.

Try 0.33.2. It should fix the problem.

**Comment by steelshot** [comment]
Yeah, that fixed it.

What I've just presumed by having the Axe, tools and block list completely empty, it should not interact with the Lumber Axe as it is not in the config, and the suggestion made was made just to more easily control the config. Why load an interaction ie Axe or Hoe, when it is not being used. I myself only use the veinminer for ores and few blocks for shovels, and have everything else empty. I know you can disable the tool/block detection, but it seems that, that ignores modded stuff and blocks/tools are being re added back in.
