### ISSUE TITLE
Released mode won't work

### ISSUE THREAD

**Issue by steelshot** [portablejim/VeinMiner#61]
I am having an issue after regenerating fresh configs, released mode just does not work, unless you use the "veinminerc" command, but that only affects the current session on the world, and after re logging into a SP or MP world goes back to pressed mode.

Both my client and server have S:client.preferredMode=released in the config.

**Comment by portablejim** [comment]
Does 0.34.0 fix it?

**Comment by steelshot** [comment]
yeah, that seems to have fixed the issue
