### ISSUE TITLE
Painted Block interference-Sky factory. 2.5.3 (Server)

### ISSUE THREAD

**Issue by Helimyne** [portablejim/VeinMiner#63]
Crash Log: https://cdn.discordapp.com/attachments/113017443089166336/200467406714437633/crash-2016-07-07_04.11.41-server.txt

Probable source; player Veinmined painted glowstone (not on purpose) floor was made of said block instead of only a few.

**Comment by portablejim** [comment]
This is old now and looking at it seems like enderio's fault.
