### ISSUE TITLE
Vanilla behavior has intended consequences

### ISSUE THREAD

**Issue by utoc** [portablejim/VeinMiner#68]
Hi there

I have noticed an issue since using VeinMiner that I'd like to see if there is a workaround.  When there is a vein of something, say lapis for example, and half the vein is on the other side of a wall but can't directly be seen, it seems that the items disappear about 1 out of 3 times.

I think this is being caused by Vanilla stacking behavior and that the "lost" and unseen items are either going for a swim in a nearby pool or lava or are in a nearby unseen void (1x1 perhaps) opened up by using the veinminer toggle.  I'm not sure really.  I just know that items tend to disappear.

Is there any way to fix this?  Or prevent it?  Do you even understand the situation I'm trying to describe?  Can you consider dropping the mined items in the place of the original block that was mined to trigger the vein mine?  Is there another way?

**Comment by SonnyX** [comment]
From what I' ve seen Veinminer combines all the items and drops them at the mined block' s location, therefor you do not loose items, you could run a few simple tests to verify this behavior.

**Comment by utoc** [comment]
Hi @SonnyX.  We've definitely run tests on this otherwise this ticket wouldn't even exist.  Thanks anyway though
