### ISSUE TITLE
[Request] Tool Blacklist

### ISSUE THREAD

**Issue by Ampflower** [portablejim/VeinMiner#71]
Be nice to blacklist the tools to NOT use veinminer, like a tool that does a big area of mining, it can cause veinminer to go crazy and mine a huge chunk of the world.

**Comment by Darkosto** [comment]
^^ This is also a feature that would be nice to have when all tools/items are usable for veinmining. People tend to get a little upset when I removed features from SkyFactory so it would be nice to remove the tools that are crashing the game out when you veinmine with them, like the Tinker's hammer.

At this point, I'm either going to have to limit what players can use manually if I want to avoid this crash. Which is especially bad on servers.

**Comment by Ampflower** [comment]
Yea. It would be nice if Veinminer has this feature.

**Comment by portablejim** [comment]
Added.
