### ISSUE TITLE
[suggestion] temporary limiting commands

### ISSUE THREAD

**Issue by 4Magma** [portablejim/VeinMiner#72]
It would be nice if i could restrict the block breaking to a specific area like the current chunk.
When i start a new world i dig a great hole at chunk borders to create a multilevel home.
So i can break the most of the blocks with veinminer, i have to dig before a trench
around the chunk, which prevent veinminer from breaking blocks outside the chunk
- restrict to x,y,z directions (e.g. only between x=7 and x=-8)
- restrict to relative x,y,z directions (e.g. only one y layer at once)
- restrict to chunk (relative to block who is first broken)
- the limits complement one another
- temporary as it should not saved with saveconfig

/veinminer limit reset
- removes all previous limitations

/veinminer limit info
- prints all active limitations to chat

/veinminer limit chunk on|off 
- activates/deactivates chunk limiting

/veinminer limit x value1 value2 [relative]
/veinminer limit y value1 value2 [relative]
/veinminer limit z value1 value2 [relative]
- restrict breaking to given range
- if relative the range is relative to starting block else to world coordinates

example:
/veinminer limit chunk on
- only break blocks who are in the same chunk as the block i break

/veinminer limit y -1 0 relative
- only break block who are same height as the starting block or one below

this way i could dig a chunk layer by layer

The limiting is mostly for pickaxe or shovel but less for axe and shears,
therefore the type of tool should be integrated in the command
/veinminer limit pickaxe ... 
Because shovel and pickaxe are comparable when digging,
multiple tools should be allowed.
/veinminer limit pickaxe,shovel ...

**Comment by lucom** [comment]
Something more user friendly would be great. Example: Use the VeinMiner-Key to cycle through different shapes like square, flat, sphere, etc. and use the scroll wheel to adjust the size.

**Comment by portablejim** [comment]
No.
