### ISSUE TITLE
Blacklist not working?

### ISSUE THREAD

**Issue by MrAmericanMike** [portablejim/VeinMiner#73]
Maybe I'm just doing it wrong, but I can't prevent veinminer for working on, for example, Stone Pressure Plates
# Blocks to not override success for

```
#  [default: [EnderIO:blockConduitBundle]]
S:override_blacklist_blocks <
    EnderIO:blockConduitBundle
    minecraft:stone_pressure_plate
 >
```

Not sure why this doesn't work

**Comment by portablejim** [comment]
It doesn't do what you think it does.

**Comment by MrAmericanMike** [comment]
Ok. And is there anyway to have a blacklist to prevent certain blocks been veinmined? I would really give good use to that feature. Thanks a lot.

PS: What does it exactly do, and why are EndeIO Conduit Bundle the default there, what other type of blocks would need to be there?
