### ISSUE TITLE
Random Crash-1.10.2

### ISSUE THREAD

**Issue by WenXin20** [portablejim/VeinMiner#75]
Forge 2062
VeinMiner 0.34.1-1.9r571+73be663
[Crash Report](http://pastebin.com/7w7eXH04)
Crash happened while veinmining the Random Ore from the Grim Pack Mod.
I already reported it the Grim Pack Mod Issue Tracker (grim3212/Grim-Pack#20)

**Comment by portablejim** [comment]
It's probably random ores doing something bad.
