### ISSUE TITLE
VM+GT5 (1.7.10) Compatibility

### ISSUE THREAD

**Issue by claws61821** [portablejim/VeinMiner#79]
I'm having trouble using Veinminer 0.34.1 with a new custom pack. While it seems to behave as intended for trees and vanilla materials, none of the players on my server are able to successfully use Veinminer on any ore block originating from Gregtech 5.09.22. The IDs for the ores and tools are entered correctly in both the server-side and client-side configuration registries. Any insight would be appreciated. Thank you for your time.

**Comment by claws61821** [comment]
Troubleshooting with help from someone who knows more about Gregtech than I do, I have been told that "GT ores are technically tile entities" and have different metadata as items and as blocks. I'm not sure how that effects Veinminer and neither is the person helping me. Manually placing ore blocks from Gregtech has no effect - they are still mined individually when the activation key is depressed.

**Comment by portablejim** [comment]
Gregtech does some funky stuff. Not adding mapping facilities just for gregtech.
