### ISSUE TITLE
[Request] Make VeinMiner slower (configurable)

### ISSUE THREAD

**Issue by lucom** [portablejim/VeinMiner#80]
Currently the slowest setting for VeinMiner is 1 block per tick. It would be great to define even slower mining rates like 1 block every 10 ticks. That way VeinMiner would become a bit more fair regarding mining speed and it would be less of a cheat.

**Comment by ShayBox** [comment]
git gud, just turn off dirt/grasss/stone mining

**Comment by portablejim** [comment]
No, not going to be implemented.
