### ISSUE TITLE
Certain blocks?

### ISSUE THREAD

**Issue by FIamuz** [portablejim/VeinMiner#82]
Is it a bug that i can only mine certain blocks with certain tools, have enabled the ord dict, and the auto detect of tools, is there a way to make it destroy all blocks with all tools, including non tools, so the open hand in general?. I have also set the option of it being "pressed" but it seems un-responsive when ever i want to use it. It is 1.10.2, downloaded a few hours ago, newest version of course.

**Comment by Starwort** [comment]
Dude, look in the .cfg file. There are options right at the bottom labeled "Override all tools" and "Override all blocks" (or something like that). Try setting that to true...
