### ISSUE TITLE
VeinMiner Crashes when Used with Any AOE Tool (Tested: Draconic Evolution AOE Tools, TConstruct Hammer)

### ISSUE THREAD

**Issue by Whimsyturtle** [portablejim/VeinMiner#92]
When VeinMiner is Used with Any AOE Tool (Tested With: Draconic Evolution AOE Tools, TConstruct Hammer), the Game Closes, bringing You Back to the Minecraft Launcher, and then Just Hangs.

Crash With Draconic Evolution AOE Tools: http://pastebin.com/gakgvNDd
Crash With TConstruct Hammer: http://pastebin.com/M7j1Pxjk

^ All Above Crash Logs have been Taken from logs\latest.log

**Comment by portablejim** [comment]
Should be fixed. Please test.

**Comment by portablejim** [comment]
Also #65 was first.

**Comment by Whimsyturtle** [comment]
Yep, it's Fixed.

But on the Side Note, it Glitches out Quite a bit.
